language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t dangpham/docker-frontend -f Dockerfile.dev .
script:
  - docker run -e CI=true dangpham/docker-frontend npm run test
